#!/usr/bin/bash

announce_starting_tests() {
    echo ""
    echo ""
    echo "compilation done, running tests"
    echo ""
    echo ""
}

cd pp_cpp/test
(g++ -Wall -pedantic -g3 -o bin/test test.cpp) \
    && announce_starting_tests \
    && ./bin/test
